#!/usr/bin/env python3
"""
Patches the Android project generated by `npx cap add android` so that:
  1. The Google Services Gradle plugin (needed for google-services.json /
     Firebase) is applied.
  2. Debug builds are signed with a fixed keystore (ci-debug.keystore,
     committed at the repo root) instead of a random ephemeral one, so the
     APK's SHA-1 fingerprint stays the same across every CI run and keeps
     matching what's registered in the Firebase console.

Safe to run multiple times (idempotent): re-running it will not duplicate
any of the inserted blocks.
"""
import re
import sys

ROOT_GRADLE = "android/build.gradle"
APP_GRADLE = "android/app/build.gradle"
VARIABLES_GRADLE = "android/variables.gradle"

SIGNING_BLOCK = """
// --- Added by scripts/patch_gradle.py: fixed debug keystore ---
android {
    signingConfigs {
        debug {
            storeFile file('../../ci-debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
    }
}
"""

GOOGLE_SIGNIN_EXT_BLOCK = """
// --- Added by scripts/patch_gradle.py: bundle the native Google Sign-In SDK ---
// Required by @capacitor-firebase/authentication, otherwise the app crashes on
// launch with: NoClassDefFoundError: Lcom/google/android/gms/auth/api/signin/GoogleSignIn
ext {
    rgcfaIncludeGoogle = true
    androidxCredentialsVersion = '1.3.0'
}
"""

GOOGLE_SERVICES_APPLY = "apply plugin: 'com.google.gms.google-services'\n"
GOOGLE_SERVICES_CLASSPATH = "        classpath 'com.google.gms:google-services:4.4.2'\n"


def patch_root_gradle():
    with open(ROOT_GRADLE, "r", encoding="utf-8") as f:
        content = f.read()

    if "com.google.gms:google-services" in content:
        print(f"[skip] {ROOT_GRADLE} already has the google-services classpath")
        return

    pattern = re.compile(r"(classpath ['\"]com\.android\.tools\.build:gradle[^\n]*\n)")
    new_content, count = pattern.subn(lambda m: m.group(1) + GOOGLE_SERVICES_CLASSPATH, content, count=1)

    if count == 0:
        print(f"[warn] could not find AGP classpath line in {ROOT_GRADLE}, appending inside buildscript dependencies not attempted")
        sys.exit(1)

    with open(ROOT_GRADLE, "w", encoding="utf-8") as f:
        f.write(new_content)
    print(f"[ok] added google-services classpath to {ROOT_GRADLE}")


def patch_app_gradle():
    with open(APP_GRADLE, "r", encoding="utf-8") as f:
        content = f.read()

    changed = False

    if "ci-debug.keystore" not in content:
        content += SIGNING_BLOCK
        changed = True
        print(f"[ok] added fixed debug signingConfig to {APP_GRADLE}")
    else:
        print(f"[skip] {APP_GRADLE} already has the fixed debug signingConfig")

    if "apply plugin: 'com.google.gms.google-services'" not in content:
        content += "\n" + GOOGLE_SERVICES_APPLY
        changed = True
        print(f"[ok] applied google-services plugin in {APP_GRADLE}")
    else:
        print(f"[skip] {APP_GRADLE} already applies the google-services plugin")

    if changed:
        with open(APP_GRADLE, "w", encoding="utf-8") as f:
            f.write(content)


def patch_variables_gradle():
    with open(VARIABLES_GRADLE, "r", encoding="utf-8") as f:
        content = f.read()

    if "rgcfaIncludeGoogle" in content:
        print(f"[skip] {VARIABLES_GRADLE} already includes rgcfaIncludeGoogle")
        return

    content += GOOGLE_SIGNIN_EXT_BLOCK
    with open(VARIABLES_GRADLE, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"[ok] enabled native Google Sign-In SDK in {VARIABLES_GRADLE}")


if __name__ == "__main__":
    patch_root_gradle()
    patch_app_gradle()
    patch_variables_gradle()
